#Abalone
https://archive.ics.uci.edu/ml/datasets/abalone

Given is the attribute name, attribute type, the measurement unit and a brief description. The number of rings is the value to predict: either as a continuous value or as a classification problem.


Name / Data Type / Measurement Unit / Description
-----------------------------
**Sex / nominal / -- / M, F, and I (infant)**

Length / continuous / mm / Longest shell measurement

Diameter / continuous / mm / perpendicular to length

Height / continuous / mm / with meat in shell

Whole weight / continuous / grams / whole abalone

Shucked weight / continuous / grams / weight of meat

Viscera weight / continuous / grams / gut weight (after bleeding)

Shell weight / continuous / grams / after being dried

**Rings / integer / -- / +1.5 gives the age in years**



#Importacicon y Limpieza de Datos

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

filename = '/content/drive/MyDrive/Coding Dojo/Semana 5/abalone.csv'
df = pd.read_csv(filename)
df.head()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Sex  Lenght  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell  Rings  
0  0.150     15  
1  0.070      7  
2  0.210      9  
3  0.155     10  
4  0.055      7

In [ ]:
from pandas.core.window.ewm import get_center_of_mass
#Cambiamos las variables texto a numericas - categoricas
generoM=df.loc[:,"Sex"]=="M"
generoF=df.loc[:,"Sex"]=="F"
generoI=df.loc[:,"Sex"]=="I"
df.loc[generoM,["Sex"]]=0
df.loc[generoF,["Sex"]]=1
df.loc[generoI,["Sex"]]=2
df["Sex"] = df["Sex"].astype('float')
df["Sex"]

0       0.0
1       0.0
2       1.0
3       0.0
4       2.0
       ... 
4172    1.0
4173    0.0
4174    0.0
4175    1.0
4176    0.0
Name: Sex, Length: 4177, dtype: float64

#Features y Values

In [ ]:
X = df.loc[:, ['Sex',	'Lenght',	'Diameter',	'Height',	'Whole_weight',	'Shucked_weight',	'Viscera_weight',	'Shell']].values
y=df.loc[:, 'Rings'].values
y.shape

(4177,)

In [ ]:
#partiremos encontrando los resultados con division
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
# Estandarizar datos con division
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)



#KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor


In [ ]:
for K in range(20):
    K = K+1
    knn = neighbors.KNeighborsRegressor(n_neighbors = K)
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    print('Score for k= ' , K , 'is:', knn.score(X_test, y_test))

Score for k=  1 is: 0.13038847871797632
Score for k=  2 is: 0.36161303307631576
Score for k=  3 is: 0.43460776966160897
Score for k=  4 is: 0.46924387047018745
Score for k=  5 is: 0.47372809336257315
Score for k=  6 is: 0.5039127375643635
Score for k=  7 is: 0.5079649414875966
Score for k=  8 is: 0.5064024410368816
Score for k=  9 is: 0.5136178897507129
Score for k=  10 is: 0.5164280910264671
Score for k=  11 is: 0.5172792157222894
Score for k=  12 is: 0.5172778205354969
Score for k=  13 is: 0.5159787557489786
Score for k=  14 is: 0.5114586939345533
Score for k=  15 is: 0.5125352283580666
Score for k=  16 is: 0.5112325744009262
Score for k=  17 is: 0.5130496757036114
Score for k=  18 is: 0.5117443546959499
Score for k=  19 is: 0.5123138821738613
Score for k=  20 is: 0.5087346241529407


In [ ]:
#ahora lo haremos sin division
scaler2 = StandardScaler()

In [ ]:
# Estandarizar datos
X_copy= X
scaler = StandardScaler()
scaler.fit(X_copy)
X_copy = scaler.transform(X_copy)


In [ ]:
knn2 = KNeighborsRegressor(n_neighbors=15)



In [ ]:
knn2.fit(X_copy, y)

KNeighborsRegressor(n_neighbors=15)

In [ ]:
predictions2 = knn2.predict(X_copy)

In [ ]:
predictions2

array([ 8.93333333,  8.73333333, 10.2       , ..., 10.6       ,
        9.66666667, 11.2       ])

In [ ]:
score2 = knn2.score(X_test, y_test)
score2

0.5828449530393621

In [ ]:
#Al hacer el train-test, el modelo por logica tiene que ser menos bueno para predecir que si le pasamos todos los datos 
#ya que dentro de estos está la info precisa de lo que predeciremos.



#Regresion lineal con y sin split

In [ ]:
from sklearn.linear_model import LinearRegression
# Hacer una instancia de regresión lineal
reg = LinearRegression(fit_intercept=True)


In [ ]:
reg.fit(X,y)


LinearRegression()

In [ ]:
reg.predict(X)

array([ 9.2423098 ,  7.81022316, 10.84388028, ..., 11.10439683,
        9.51353803, 11.14402922])

In [ ]:
y

array([15,  7,  9, ...,  9, 10, 12])

In [ ]:
score_reg = reg.score(X, y)
score_reg

0.5353445764938826

In [ ]:
#ahora con train-test
reg2 = LinearRegression(fit_intercept=True)

In [ ]:
reg2.fit(X_train,y_train)

LinearRegression()

In [ ]:
reg.predict(X_test)

array([ 4.13861168, 14.71954596, -1.77761848, ..., -6.11795471,
       -4.69707214, 16.23916563])

In [ ]:
score_reg2 = reg2.score(X_test, y_test)
score_reg2

0.5028540530581911

In [ ]:
##¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando no usaste la división entrenar probar?
#Cuando no use la division me funciono mejor el KNN
##¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando usaste la división entrenar probar?
#para diferentes valores de k me dio muy diferentes resultados y algunos tambien gano knn
##¿Hubo alguna ventaja en la regresión lineal en términos de la cantidad de código que tenías que escribir?
#Si, bastante menos
##¿Hay alguna forma de mostrarle a alguien cuál de los dos modelos fue más efectivo?
#usando los datos de train es mas efectivo el modelo porque se prueba con datos no vistos con anterioridad
##¿Crees que podrías haber mejorado KNN para mejorar la eficacia del modelo?
#Creo que si hay bastantes cosas por hacer como seleccionar mejor la data a usar, cambiar lso pesos especificos entre otros.
